Feature/35 Aanmaken van zorgmedewerkers
MelvinHsieh/VirtualAssistant pull request #28
Opened 2022-05-04 08:48 UTC by 0xboomie

2022-05-04 11:31 UTC, RyanWennekes requested changes
Ziet er goed uit. Zit een overbodige file in die straks gaat clashen met je andere PR.

Verder wil ik ook nog even bij deze oproepen om het in de retro te hebben over foreign key gebruik. Eerder hebben we al besloten dat we properties niet includen, maar rechtstreeks in de origin table zetten (e.g. CareWorkerFunction op CareWorker model is een string, geen object). Deze manier van werken zit me niet super lekker, ook al begrijp ik het argument ook dat dit kolomvelden zijn die we idealiter nooit hoeven aan te passen. Ik denk namelijk dat dit iets is waar we op worden afgerekend in de beoordeling als we dit niet expliciet met Martijn hebben besproken.

Voor nu echter: alleen die Okteto workflow file weghalen en dan ziet het er helemaal mooi uit.

2022-05-04 11:31 UTC, RyanWennekes commented on .github/workflows/okteto-preview.yml
> +  pull_request:
Deze file hoort niet thuis in deze PR. Om de commit history clean te houden zou ik deze verwijderen.

2022-05-05 06:51 UTC, 0xboomie commented on .github/workflows/okteto-preview.yml
> +  pull_request:
Hey, ik heb deze branche gebaseerd op de okteto branche, daarom zit de file er in. Ik heb dit gedaan omdat de solution compleet is omgegooid in de okteto branche, en ik hiervoor uit gemak er voor heb gekozen om deze branche op de okteto te baseren

2022-05-05 11:25 UTC, MelvinHsieh approved these changes

2022-05-05 12:19 UTC, MelvinHsieh approved these changes

2022-05-05 12:19 UTC, KBelt approved these changes

2022-05-05 12:22 UTC, merged