Android/feature/show medicine planning
MelvinHsieh/VirtualAssistant pull request #30
Opened 2022-05-06 16:12 UTC by KBelt

Show Medicine planning, text to speech and Wake Word Engine functionality.

2022-05-07 08:56 UTC, ntjhal approved these changes
Ziet er goed uit, kan hem helaas niet runnen om te testen. Mocht iemand daar tijd voor hebben zou dat fijn zijn

2022-05-08 11:35 UTC, RyanWennekes requested changes
Lekker gewerkt pik. Goed om te zien dat porcupine in z'n eigen service staat. Nog een paar comments achtergelaten, voornamelijk mbt applicatie structuur.

2022-05-08 11:35 UTC, RyanWennekes commented on bot/Bot/Dialogs/Assistance/SubDialogs/RegisterIntakeDialog.cs
> +            if (stepContext.Result.ToString().ToLower() == "ja" || stepContext.Result.ToString().ToLower() == "ja.")
Ik stel voor dat je wacht met de merge totdat Niels' PR voor confirmation intents erdoorheen is. Dan even mergen met dev en die changes ook in de bot laten zien. In principe hoeven we niet meer met hardcoded 'ja' of 'nee' te werken :)

2022-05-08 11:35 UTC, RyanWennekes commented on mobileapp/app/src/main/java/com/infosupport/virtualassistent/MainActivity.java
> +    public void formatSchedule(JSONObject msg) {
Ik zie dit het liefst in een dedicated schedule folder. De MainActivity dreigt nu een god class te worden

2022-05-08 11:35 UTC, RyanWennekes commented on mobileapp/fastlane/Fastfile
> +  desc "Deploy a beta version to the Google Play"
Kan deze file niet weg, aangezien we erachter kwamen dat auto deploy naar de playstore niet slaagde? Geldt voor heel de fastlane folder.

correct me if I'm wrong.

2022-05-09 08:07 UTC, RyanWennekes approved these changes

2022-05-09 08:07 UTC, merged