Feature/save interaction
MelvinHsieh/VirtualAssistant pull request #36
Opened 2022-05-13 08:03 UTC by 0xboomie

Alle interactie tussen bot en user worden opgeslagen in een mongo db.
Voorbeeld:
![image](https://user-images.githubusercontent.com/43607639/168238874-130ad996-6379-47ba-97ed-34350b323960.png)

Er kunnen 1 of meerdere replies opgeslagen worden

2022-05-13 13:10 UTC, MerijnMonfils commented on loggingservice/package.json
> +  "version": "0.0.0",
Misschien niet versie 0.0.0 hebben?

2022-05-13 13:14 UTC, MerijnMonfils requested changes
Ik heb nog een suggestie, dat er een datetime aan verbonden is.

2022-05-17 10:22 UTC, RyanWennekes requested changes
Ziet er goed uit.

Wat comments achtergelaten.

Er missen nog api endpoints op de logging service om gelogde data ook weer op te halen, maar dat hoort volgens mij niet tot jouw user story. Verwijder dan wel even de routes uit het logging service project (en de verwijzingen in app.js). Verder kunnen mijns inziens alle views (.jade) verwijderd worden uit de logging service (en ook hier alle config die ermee te maken heeft in app.js).

2022-05-17 10:22 UTC, RyanWennekes commented on bot/Bot/Producer/RabbitMQProducer.cs
> +            var connection = factory.CreateConnection();
Connectie wordt met iedere message gelegd? Is het niet een beter idee om de connectie te initializeren en de klasse dan als singleton overal aan te roepen?

2022-05-17 10:22 UTC, RyanWennekes commented on bot/Bot/Utils/LoggingService.cs
> +                        if(messageActivity.Text != "Welkom!" &&
Dit vereist wat werk vanuit de bot vrees ik. Er wordt nu inderdaad een Activiteit verstuurd van het type 'message', dus wat dat betreft kunnen we op dit moment alleen maar kijken naar de content van de activity, zoals je hier ook doet. Als we de introtekst aan willen passen gaat de loggin service nu wel falen.

Ik zou de "Welkom" en "Waar kan ik u vandaag mee helpen?" verplaatsen naar een aparte resource file, en die aan laten roepen door zowel deze service als het deel in de bot dat er naar verwijst. Zo voorkom je in ieder geval dat het stuk gaat.

2022-05-17 10:22 UTC, RyanWennekes commented on loggingservice/consumers/storeInteraction.js
> +            // if (image) {
Even heel het comment block verwijderen x)

2022-05-19 09:25 UTC, 0xboomie commented on bot/Bot/Producer/RabbitMQProducer.cs
> +            var connection = factory.CreateConnection();
Dat kan, maar wanneer de connectie dan verbroken wordt krijg je errors. Daarnaast heb ik deze code gedeeltelijk van de RabbitMQ documentatie, dus ik ga er van uit dat het klopt. 

Ik heb het nu opgelost door de connectie ook te closen.

2022-05-19 09:28 UTC, 0xboomie commented on bot/Bot/Utils/LoggingService.cs
> +                        if(messageActivity.Text != "Welkom!" &&
Loggingservice faalt dan niet, alleen de welkom en waar kan ik u mee helpen komen dan ook in de loggingservice. Ik snap het gedeelte van resource files niet, zou je me daar mee kunnen helpen?

2022-05-19 11:21 UTC, MerijnMonfils approved these changes

2022-05-19 11:25 UTC, RyanWennekes commented on bot/Bot/Utils/LoggingService.cs
> +                        if(messageActivity.Text != "Welkom!" &&
@0xboomie Niet precies, ze komen in de LoggingService klasse, maar die staat ook in het bot project ;D

2022-05-19 11:27 UTC, RyanWennekes requested changes

2022-05-19 11:27 UTC, RyanWennekes commented on loggingservice/consumers/storeInteraction.js
> +            // if (image) {
@0xboomie Bij mij staat de comment er nog?

2022-05-19 11:28 UTC, RyanWennekes approved these changes

2022-05-19 11:28 UTC, merged