Feature/web/intake
MelvinHsieh/VirtualAssistant pull request #37
Opened 2022-05-17 11:56 UTC by MerijnMonfils

Creating intake view

2022-05-18 12:30 UTC, ntjhal approved these changes
Looks good, but also here we're pushing appsettings.development to origin which should not be the case

2022-05-19 11:23 UTC, RyanWennekes requested changes
Ziet er wederom goed uit. Wat comments achtergelaten.

2022-05-19 11:23 UTC, RyanWennekes commented on web/web/Controllers/PatientController.cs
> +        // GET: PatientController/Show/5
Deze comment lijkt niet te kloppen, correct? (als in, de patientcontroller/show/id path)

2022-05-19 11:23 UTC, RyanWennekes commented on web/web/Models/IntakeModel.cs
> +        [ScaffoldColumn(false)]
Ik zie een aantal properties een ScaffoldColumn(false) attribute hebben, maar ook een aantal niet. Aangezien de migrations vanuit de dataservice gerund worden, kunnen deze allemaal weggelaten worden neem ik aan?

2022-05-19 11:23 UTC, RyanWennekes commented on web/web/web.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.4" />
Busted ;D

2022-05-20 12:29 UTC, MerijnMonfils commented on web/web/web.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.4" />
:)

2022-05-20 12:30 UTC, MerijnMonfils commented on web/web/Controllers/PatientController.cs
> +        // GET: PatientController/Show/5
Ter verduidelijking van dat de create method bedoelt is voor intake schemas, kan overbodig overkomen idd.

2022-05-20 12:30 UTC, MerijnMonfils commented on web/web/Models/IntakeModel.cs
> +        [ScaffoldColumn(false)]
Scaffolding is voor Razor, voor code generation, dan skipt hij de Id input fields te genereren in de form, is nu idd niet meer van belang

2022-05-20 12:37 UTC, merged