Feature/linkpatient
MelvinHsieh/VirtualAssistant pull request #38
Opened 2022-05-18 02:55 UTC by MelvinHsieh

(Ont)koppeling kan nu worden verricht met behulp van: PUT api/patient/{id}

2022-05-18 12:26 UTC, ntjhal reviewed
Appsettings development niet pushen naar origin.
Waarom is de poort van de dataservice veranderd?

2022-05-19 11:07 UTC, ntjhal approved these changes
Code ziet er verder goed uit.

2022-05-19 11:58 UTC, RyanWennekes requested changes

2022-05-19 11:58 UTC, RyanWennekes commented on dataservice/dataservice/Controllers/PatientController.cs
> -        // PUT api/<PatientController>/5 NO EDIT FUNCTIONALITY YET
Comment mag weg nu?

2022-05-19 11:58 UTC, RyanWennekes commented on dataservice/Infrastructure/Migrations/MedicineDbMigrations/20220518023608_AddIntakeRegistration.cs
> +﻿using System;
Wat mij betreft geen issue voor nu, maar wel iets om op te letten:

Ik zie dat je de migrations hebt geremoved en vervolgens add-migration hebt gedraaid, waardoor alle query steps nu in één migration zitten. Dat zou in de toekomst een probleem kunnen zijn voor 2 redenen:
1. Naamgeving is verwarrend. In deze migration gebeurt veel meer dan alleen het adden van intake registration related tabellen/kolommen. Maar veel belangrijker:
2. We moeten nu de volledige productie, dev database verwijderen om de migration succesvol te kunnen laten slagen, want binnen de db staat nu geregistreerd dat de eerdere drie migrations als gerund zijn. Dat is nu dus geen probleem want we hebben geen klantdata, maar wel iets wat je leven gaat redden wanneer je hier ooit in aanraking mee komt. Ook kunnen we geen migration meer terugdraaien zonder álles terug te draaien (want alle stappen om dat te doen zitten nu in één method (Down())

2022-05-20 03:03 UTC, MelvinHsieh commented on dataservice/dataservice/Controllers/PatientController.cs
> -        // PUT api/<PatientController>/5 NO EDIT FUNCTIONALITY YET
functionality zit er nu in dus kan weg :)

2022-05-20 12:27 UTC, RyanWennekes approved these changes

2022-05-20 12:27 UTC, merged