Feature/auth
MelvinHsieh/VirtualAssistant pull request #43
Opened 2022-05-20 17:59 UTC by ntjhal

Authenticatie is geimplementeerd op basis van JWT, hiervoor is een aparte service beschikbaar die draait op localhost:3001 en een database die draait op 20178 (docker compose up -d authdb).

Wanneer je de authenticatie gaat testen kun je gebruik maken van een aantal seeded users. 
admin1 - admin!1
employee1 - employee!1
employee2 - employee!2
patient1 - patient!1
patient2 - patient!2

Natuurlijk kun je ook nieuwe gebruikers aanmaken

2022-05-21 20:06 UTC, KBelt reviewed
De secret van authservice/.env moet denk ik niet worden meegenomen 😨

2022-05-21 20:09 UTC, KBelt reviewed
Ook in dataservice/dataservice/appsettings.json worden wachtwoorden en secrets meegepust, is dat de bedoeling? Deze repo is public

2022-05-21 20:10 UTC, KBelt reviewed
In de app bij  mobileapp/app/src/main/java/com/infosupport/virtualassistent/services/AuthService.java staat mijn local ip nog hardcoded, die moet nog naar de auth endpoint gaan

2022-05-22 14:57 UTC, RyanWennekes reviewed
Ik wilde hier in de trein even naar kijken, maar ik denk dat ik hier wat langer voor nodig heb. Mocht iemand hem in de tussentijd approven kan je mn review dismissen.

2022-05-22 14:57 UTC, RyanWennekes commented on authservice/app.js
> +app.set('view engine', 'jade');
Kan weg :)

2022-05-22 14:57 UTC, RyanWennekes commented on authservice/app.js
> +  res.render('error');
Moet JSON retourneren denk ik.

2022-05-23 13:48 UTC, RyanWennekes requested changes
Ziet er over het algemeen goed uit. Een aantal comments achtergelaten.

2022-05-23 13:48 UTC, RyanWennekes commented on authservice/globalConfig.json
> +{"mongoUri":"mongodb://127.0.0.1:54341/"}
Ik zou deze persoonlijk ook verplaatsen naar docker-compose. Dan hebben we straks voor iedere applicatie configuratie op één locatie staan.

2022-05-23 13:48 UTC, RyanWennekes commented on authservice/public/stylesheets/style.css
> +body {
Mag weg denk ik :)

2022-05-23 13:48 UTC, RyanWennekes commented on authservice/views/error.jade
> +extends layout
Alle views mogen weg denk ik.

2022-05-23 13:48 UTC, RyanWennekes commented on dataservice/dataservice/appsettings.json
> +    "PatientConnection": "Server=tcp:dataservicedbserver.database.windows.net,1433;Database=userdatadb;User Id=virtualassistent;Password=VirtualAssistantPass12345!@;",
Dit moet weer even terugveranderd worden.

2022-05-23 13:48 UTC, RyanWennekes commented on mobileapp/app/src/main/java/com/infosupport/virtualassistent/services/AuthService.java
> +        String url = "http://localhost:3001/login"; //inject??
Dit kan inderdaad het best in config.xml, waar ook alle andere urls staan

2022-05-23 13:48 UTC, RyanWennekes commented on web/web/Program.cs
> +/*builder.Services.AddAuthentication(options =>
Is de uitgecommente code nog relevant?

2022-05-23 15:20 UTC, RyanWennekes commented on docker-compose.yml
> +  authdb_volume:
Je bent hier overigens wel vergeten de authservice daadwerkelijk in de docker-compose te zetten.

2022-05-23 15:21 UTC, RyanWennekes commented on docker-compose.yml
> +  authdb_volume:
Ook de authdb

2022-05-23 15:44 UTC, RyanWennekes commented on docker-compose.yml
> +  authdb_volume:
Ik pak dit wel op, want anders kan deze PR er niet voor morgen doorheen

2022-05-29 09:19 UTC, MerijnMonfils commented
deze kan pas gemerged worden wanneer @RyanWennekes zijn RFC dismissed of resolved

2022-05-30 11:40 UTC, KBelt approved these changes

2022-05-30 11:42 UTC, MerijnMonfils approved these changes

2022-05-30 11:44 UTC, merged