Feature graphical represitation
MelvinHsieh/VirtualAssistant pull request #49
Opened 2022-06-05 13:14 UTC by MelvinHsieh

secrets eruit gehaald

2022-06-05 13:18 UTC, RyanWennekes approved these changes
Hier word ik gelukkig van.

2022-06-06 17:23 UTC, KBelt requested changes
Deze pull request NIET voor de demo mergen. Dit breekt de changes van feature/emergency

2022-06-06 17:24 UTC, RyanWennekes commented
> Deze pull request NIET voor de demo mergen. Dit breekt de changes van feature/emergency

Mee eens. We hebben variable injection bewust gesloopt om morgen te kunnen demo-en. Leg ik zo ook even aan het team voor.

2022-06-07 07:07 UTC, ntjhal approved these changes

2022-06-10 11:31 UTC, KBelt approved these changes

2022-06-10 11:31 UTC, merged